-- SQL Script สำหรับ Supabase
create table hospitals (
  id bigint generated by default as identity primary key,
  name text not null,
  area text,
  is_checked boolean default false,
  checked_at timestamp with time zone,
  latitude numeric,
  longitude numeric,
  image_url text,
  note text
);

insert into hospitals (id, name, area, latitude, longitude) values
  (1, 'รพ.สต.บ้านปากแคว', 'ต.ปากแคว', 17.0345, 99.8182),
  (2, 'โรงพยาบาลส่งเสริมสุขภาพตำบลยางซ้าย', 'ต.ยางซ้าย', 16.9452, 99.8211),
  (3, 'โรงพยาบาลส่งเสริมสุขภาพตำบลตำบลบ้านกล้วย', 'ต.บ้านกล้วย', 17.0012, 99.7821),
  (4, 'โรงพยาบาลส่งเสริมสุขภาพตำบลปากพระ', 'ต.ปากพระ', 17.1120, 99.8315),
  (5, 'โรงพยาบาลส่งเสริมสุขภาพตำบลหนองตูม', 'ต.หนองตูม', 16.9231, 99.9812);
